# Generated by Django 5.1 on 2025-02-12 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название')),
                ('about', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank='True', max_length=60, null=True, verbose_name='Название')),
                ('img', models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Изображение')),
                ('price', models.FloatField(blank='True', null=True, verbose_name='Цена')),
                ('weight', models.FloatField(blank='True', null=True, verbose_name='Вес')),
                ('description', models.TextField(blank='True', null=True, verbose_name='Описание')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Состав')),
                ('nutritional_value', models.TextField(blank=True, null=True, verbose_name='Пищевая ценность')),
                ('category_filter', models.CharField(choices=[('frost', 'frost'), ('mini_cake', 'mini_cake'), ('cake', 'cake')], default='cake', max_length=20)),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликовано')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery.category')),
            ],
            options={
                'verbose_name': 'продукция',
                'verbose_name_plural': 'продукции',
            },
        ),
    ]
