# Generated by Django 5.1 on 2025-02-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category_filter',
            field=models.CharField(choices=[('cake', 'cake'), ('mini_cake', 'mini_cake'), ('frost', 'frost')], default='cake', max_length=20),
        ),
    ]
