# Generated by Django 5.1 on 2024-10-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0003_products_category_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category_filter',
            field=models.CharField(choices=[('mini_cake', 'mini_cake'), ('frost', 'frost'), ('cake', 'cake')], default='cake', max_length=20),
        ),
    ]
