# Generated by Django 5.1 on 2024-11-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0005_alter_products_category_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category_filter',
            field=models.CharField(choices=[('cake', 'cake'), ('mini_cake', 'mini_cake'), ('frost', 'frost')], default='cake', max_length=20),
        ),
    ]
