# Generated by Django 5.1 on 2024-10-30 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0005_alter_products_category_filter'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrederItem',
            new_name='OrderItem',
        ),
    ]
